import type { Metadata } from "next";
import "./theme.css";
import RecoilRootProvider from "@/components/provider/RecoilRootProvider";
import Header from "@/components/common/header/Header";
import Providers from "./Provider";
import { Noto_Sans_KR } from "next/font/google";

export const metadata: Metadata = {
  title: "Shopping MAll",
  description: "Generated by create next app",
};

const noto_sans = Noto_Sans_KR({
  subsets: ["latin"],
  variable: "--font-noto-sans",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${noto_sans.variable}`}>
      <body>
        <Providers>
          <RecoilRootProvider>
            <Header />
            {children}
          </RecoilRootProvider>
        </Providers>
      </body>
    </html>
  );
}
