import type { Metadata } from "next";
import "./theme.css";
import RecoilRootProvider from "@/components/provider/RecoilRootProvider";

export const metadata: Metadata = {
  title: "Shopping MAll",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  );
}
